### PR TITLE
refactor: fix c-spell warning

### PR DESCRIPTION
**Pull request by netanelC**
Fix wrong words

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✖                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✖                                                                        |
| Chore            | ✔                                                                       |

### CODE REVIEW

**Comment by CptSchnitz** [comment]
not chore

**Comment by netanelC** [comment]
> not chore

**Comment by netanelC** [comment]
> > not chore

Thanks. Fixed to refactor

**Comment by netanelC** [comment]
Fixed to refactor

**Review by shimoncohen — APPROVED** [review]

**Pull request merged**
